name: Test Installer

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update && apt-get install -y git sudo
    - name: Run installer
      run: sudo ./install.sh
  
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run installer
      run: ./install.sh