name: Test Installer

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    # container: ubuntu:20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt update && apt install -y expect
        expect -c "
        set timeout 300
        spawn apt install -y pkg-config
        expect \"Geographic area:\"
        send \"2\n\"
        expect \"$\"
        exit 0
        "
        apt install -y libssl-dev build-essential git
    - name: Install python dependencies
      run: apt install -y gdb lcov libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev libreadline6-dev libsqlite3-dev lzma lzma-dev tk-dev uuid-dev zlib1g-dev
    - name: Install zsh
      run: apt install --no-install-recommends -y zsh
    - name: Run installer
      run: zsh ./install.sh -e

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install homebrew
      run: NONINTERACTIVE=1 /bin/bash -c "$(curl --proto '=https' --tlsv1.2 -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Run installer
      run: zsh ./install.sh --extra