name: Test Installer

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt update
        expect -c "
        set timeout 300
        spawn apt install -y pkg-config
        expect \"Geographic area:\"
        send \"2\n\"
        expect \"$\"
        exit 0
        "
        apt install -y libssl-dev build-essential
    # - name: export openssl
    #   # run: export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu && export OPENSSL_INCLUDE_DIR=/usr/include/openssl
    #   run: export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include && export DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include
    - name: Install zsh
      run: apt install --no-install-recommends -y zsh
    - name: Run installer
      run: zsh ./install.sh

  
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install homebrew
      run: NONINTERACTIVE=1 /bin/bash -c "$(curl --proto '=https' --tlsv1.2 -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Run installer
      run: zsh ./install.sh